name: Update ip.txt with HK & KR IPs

//on:
  schedule:
    - cron: '0 2 * * *'      # 每天 02:00 UTC
  workflow_dispatch:          # 手动触发

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Download & unzip
        run: |
          curl https://zip.cm.edu.kg > ip.zip
          unzip -j ip.zip "*/HK.txt" "*/KR.txt" -d tmp/

      - name: Merge HK & KR → ip.txt
        run: |
          cat tmp/HK.txt tmp/KR.txt > ip.txt

      - name: Commit & push
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add ip.txt
          git diff --cached --quiet || git commit -m "Auto-update ip.txt from HK.txt & KR.txt"
          git push
